export const newOrdersTableData = [
    {
slNo:1,
billNo:"#8434",
orderId:"2134",
menu1:"Burger",
menu2:"Pizza",
specialInstructions:"No onions",
quantity:2,
orderTime:"12:00 PM",
tableNo:3,
    },
    {
        slNo:2,
        billNo:"#5434",
        orderId:"4329",
        menu1:"Bririyani",
        menu2:"Pizza",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:2,
    },
    {
        slNo:3,
        billNo:"#6434",
        orderId:"7334",
        menu1:"Orange Juice",
        menu2:"Puffs",
        specialInstructions:"No Sugar",
        quantity:2,
        orderTime:"12:00 PM",   
        tableNo:7,
    },
]
export const OngoingOrdersTableData = [
    {
slNo:1,
orderId:"1234",
menu:"Burger",
specialInstructions:"No onions",
quantity:2,
orderTime:"12:00 PM",
tableNo:3,
serveTime:"12:30 PM",

    },
    {
        slNo:2,
        orderId:"4329",
        menu:"Bririyani",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
    },
    {
        slNo:3,
        orderId:"4234",
        menu:"Sandwich",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",   
        tableNo:3,
        serveTime:"12:30 PM",
    },
    {
        slNo:4,
        orderId:"4334",
        menu:"Pizza",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
    },
    {
        slNo:5,
        orderId:"9234",
        menu:"Pasta",
        specialInstructions:"More cheese",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
    },

]

export const completedOrdersTableData = [
    {
slNo:1,
orderId:"1234",
menu:"Burger",
specialInstructions:"No onions",
quantity:2,
orderTime:"12:00 PM",
tableNo:3,
serveTime:"12:30 PM",
payment: "Cash",

    },
    {
        slNo:2,
        orderId:"4329",
        menu:"Bririyani",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Card",
    },
    {
        slNo:3,
        orderId:"4234",
        menu:"Sandwich",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",   
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Cash",
    },
    {
        slNo:4,
        orderId:"4334",
        menu:"Pizza",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Card",
    },
    {
        slNo:5,
        orderId:"9234",
        menu:"Pasta",
        specialInstructions:"More cheese",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Cash",
    },

]
export const paymentPendingOrdersTableData = [
    {
slNo:1,
orderId:"1234",
menu:"Burger",
specialInstructions:"No onions",
quantity:2,
orderTime:"12:00 PM",
tableNo:3,
serveTime:"12:30 PM",
payment: "Cash",
amount: "₹200",

    },
    {
        slNo:2,
        orderId:"4329",
        menu:"Bririyani",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Card",
        amount: "₹240",
    },
    {
        slNo:3,
        orderId:"4234",
        menu:"Sandwich",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",   
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Cash",
        amount: "₹180",
    },
    {
        slNo:4,
        orderId:"4334",
        menu:"Pizza",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Card",
        amount: "₹300",
    },
    {
        slNo:5,
        orderId:"9234",
        menu:"Pasta",
        specialInstructions:"More cheese",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Cash",
        amount: "₹220",
    },

]


export const cancelledOrdersTableData = [
    {
slNo:1,
orderId:"1234",
menu:"Burger",
specialInstructions:"No onions",
quantity:2,
orderTime:"12:00 PM",
tableNo:3,
serveTime:"12:30 PM",
payment: "Cash",

    },
    {
        slNo:2,
        orderId:"4329",
        menu:"Bririyani",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Card",
    },
    {
        slNo:3,
        orderId:"4234",
        menu:"Sandwich",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",   
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Cash",
    },
    {
        slNo:4,
        orderId:"4334",
        menu:"Pizza",
        specialInstructions:"No onions",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Card",
    },
    {
        slNo:5,
        orderId:"9234",
        menu:"Pasta",
        specialInstructions:"More cheese",
        quantity:2,
        orderTime:"12:00 PM",
        tableNo:3,
        serveTime:"12:30 PM",
        payment: "Cash",
    },

]